name: Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, iconv, json, mbstring, tokenizer
          coverage: none
      - run: composer install --ignore-platform-reqs --no-interaction
      - run: composer run tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: curl, iconv, json, mbstring, tokenizer
          coverage: pcov
      - run: composer install --no-interaction
      - run: composer run tests-with-coverage
      - uses: codecov/codecov-action@v1

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
      - run: composer install --no-interaction
      - run: composer run phpstan -- --no-progress --no-interaction

  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
      - run: composer install --no-interaction
      - run: composer run check-code-style
